# -*- coding: utf-8 -*-
"""kMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfZlYLotU06NN644KJDPhvaG76CiLRsO
"""

import pandas as pd
import numpy as np
df=pd.read_csv('/content/iris.csv')

df.head()

#but it has target column

df['class'].value_counts()

new_df = df.iloc[:,:-1]
new_df.head()

#now it has no target column

from sklearn import cluster

error=[]
for i in range (1,11):
  kmeans = cluster.KMeans(n_clusters=i,init='k-means++',random_state=0) #kmeans ++ is for centroid
  kmeans.fit(new_df)
  error.append(kmeans.inertia_) #error calculation

error

#plot the errors(y-axis) and no.of clusters(x-axis)
import matplotlib.pyplot as plt
plt.plot(range(1,11),error)
plt.title('Elbow Method')
plt.xlabel('no.of clusters')
plt.ylabel('error')

#clearly we can say k=3 and cluster values into 3 groups
km_model=cluster.KMeans(n_clusters=3,init='k-means++',random_state=0)
km_model.fit(new_df)

km_model.predict(new_df)

#test the model with random observation
km_model.predict([[1.1,2.2,4.3,4.4]])

#it belongs to 0th cluster

km_model.predict([[2.2,2.0,1.3,1.4]])

#it belongs to 1st cluster

